export 'castAndCrew.widget.dart';
export 'castCard.widget.dart';
export 'category.widget.dart';
export 'genres.widget.dart';
export 'movieCard.widget.dart';
export 'nowPlaying.widget.dart';
export 'playVideo.widget.dart';
export 'titleDuration.widget.dart';
export 'profile.item.widget.dart';